# stages:
#   - release

# release:
#   stage: release
#   image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/docker:stable
#   services:
#     - docker:dind

#   variables:
#     # Optionally use GitLab's built-in image registry.
#     # DOCKER_REGISTRY: $CI_REGISTRY
#     # DOCKER_USERNAME: $CI_REGISTRY_USER
#     # DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD

#     # Or, use any registry, including the official one.
#     DOCKER_REGISTRY: https://index.docker.io/v1/

#     # Disable shallow cloning so that goreleaser can diff between tags to
#     # generate a changelog.
#     GIT_DEPTH: 0

#   # Only run this release job for tags, not every commit (for example).
#   only:
#     refs:
#       - tags

#   script: |
#     docker run --rm --privileged \
#       -v $PWD:/go/src/gitlab.com/smcgeown/cs-cli \
#       -w /go/src/gitlab.com/smcgeown/cs-cli \
#       -v /var/run/docker.sock:/var/run/docker.sock \
#       -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
#       -e GITLAB_TOKEN \
#       harbor-repo.vmware.com/dockerhub-proxy-cache/goreleaser/goreleaser release --rm-dist
